package org.store.audit.domain.enums;

public enum AuditAction {
    EMPLOYE_CREATED,
    EMPLOYE_UPDATED,
    EMPLOYE_ACTIVATED,
    EMPLOYE_DEACTIVATED,
    EMPLOYE_DELETED,
    EMPLOYE_ROLE_ASSIGNED,
    LOGIN,
    LOGOUT,
    STOCK_ADJUSTMENT,
    STOCK_INITIAL_ENTRY,
    VENTE_CANCELLED,
    SALE_LIGNE_DELIVERY_UPDATED,
    ACHAT_CANCELLED,
    PIECE_JOINTE_AJOUTEE,
    PIECE_JOINTE_SUPPRIMEE,
    PAIEMENT_ABONNEMENT_VALIDATED,
    PAIEMENT_ABONNEMENT_REJECTED,
    DEPENSE_PLATEFORME_CREATED,
    DEPENSE_PLATEFORME_UPDATED,
    DEPENSE_PLATEFORME_DELETED,
    CATEGORY_DEPENSE_PLATEFORME_CREATED,
    CATEGORY_DEPENSE_PLATEFORME_UPDATED,
    CATEGORY_DEPENSE_PLATEFORME_DELETED
}
