package org.store.audit.domain.enums;

public enum AuditAction {
    EMPLOYE_CREATED,
    EMPLOYE_UPDATED,
    EMPLOYE_ACTIVATED,
    EMPLOYE_DEACTIVATED,
    EMPLOYE_DELETED,
    EMPLOYE_ROLE_ASSIGNED,
    LOGIN,
    LOGOUT,
    STOCK_ADJUSTMENT,
    STOCK_INITIAL_ENTRY,
    VENTE_CANCELLED,
    ACHAT_CANCELLED,
    PAIEMENT_ABONNEMENT_VALIDATED,
    PAIEMENT_ABONNEMENT_REJECTED
}
