spring:
  datasource:
    url: jdbc:postgresql://${URL_DATABASE}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true

security:
  rbac:
    sync: ${RBAC_SYNC:true}
    admin-password: ${RBAC_ADMIN_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}

app:
  mail:
    host:     ${MAIL_HOST}
    port:     ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from:     ${MAIL_FROM}
    auth:     true
    starttls: true
