package org.store.security.application.enums;

public enum PermissionCode {
    OWNER_ACCESS,
    EMPLOYE_ACCESS,
    EMPLOYE_CREATE,
    EMPLOYE_READ,
    EMPLOYE_UPDATE,
    EMPLOYE_DELETE,
    EMPLOYE_RESET_PASSWORD,
    EMPLOYE_PURGE,
    ADMIN_ACCESS,

    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,

    CONTACT_READ,
    CONTACT_RESPOND,

    // Module-level access tickets — gate the sidebar entry and the module
    // shell. Inside each module, per-screen CRUD permissions still filter
    // sub-nav tabs and row actions.
    ENTREPRISE_ACCESS,
    SETTINGS_ACCESS,
    SALES_ACCESS,
    PURCHASES_ACCESS,
    STOCK_ACCESS,
    INVENTORY_ACCESS,
    EXPENSES_ACCESS,
    CATEGORY_EXPENSE_ACCESS,

    CATEGORY_PRODUCT_CREATE,
    CATEGORY_PRODUCT_READ,
    CATEGORY_PRODUCT_UPDATE,
    CATEGORY_PRODUCT_DELETE,

    QUALITY_CREATE,
    QUALITY_READ,
    QUALITY_UPDATE,
    QUALITY_DELETE,

    PRODUCT_CREATE,
    PRODUCT_READ,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    SUPPLIER_CREATE,
    SUPPLIER_READ,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,

    CLIENT_CREATE,
    CLIENT_READ,
    CLIENT_UPDATE,
    CLIENT_DELETE,

    STOCK_READ,
    STOCK_ENTRY,
    STOCK_EXIT,
    STOCK_ADJUSTMENT,
    STOCK_INVENTORY,
    STOCK_TRANSFER,

    INVENTORY_READ,
    INVENTORY_CREATE,
    INVENTORY_WRITE,
    INVENTORY_BILAN,
    INVENTORY_CLOSE,
    INVENTORY_CANCEL,

    PLAN_CREATE,
    PLAN_READ,
    PLAN_UPDATE,
    PLAN_DELETE,

    TYPE_PLAN_CREATE,
    TYPE_PLAN_READ,
    TYPE_PLAN_UPDATE,
    TYPE_PLAN_DELETE,

    COUPON_CREATE,
    COUPON_READ,
    COUPON_UPDATE,
    COUPON_DELETE,

    PROMOTION_CREATE,
    PROMOTION_READ,
    PROMOTION_UPDATE,
    PROMOTION_DELETE,

    SUBSCRIPTION_CREATE,
    SUBSCRIPTION_READ,
    SUBSCRIPTION_UPDATE,
    SUBSCRIPTION_CANCEL,
    SUBSCRIPTION_PAY,
    SUBSCRIPTION_RENEW,
    SUBSCRIPTION_VALIDATE,

    MOYEN_PAIEMENT_CREATE,
    MOYEN_PAIEMENT_UPDATE,
    MOYEN_PAIEMENT_DELETE
}
