package org.store.security.application.enums;

public enum PermissionCode {
    PROPRIETAIRE_ACCESS,
    EMPLOYE_ACCESS,
    EMPLOYE_CREATE,
    EMPLOYE_READ,
    EMPLOYE_UPDATE,
    EMPLOYE_DELETE,
    EMPLOYE_RESET_PASSWORD,
    ADMIN_ACCESS,

    CATEGORY_PRODUCT_CREATE,
    CATEGORY_PRODUCT_READ,
    CATEGORY_PRODUCT_UPDATE,
    CATEGORY_PRODUCT_DELETE,

    QUALITY_CREATE,
    QUALITY_READ,
    QUALITY_UPDATE,
    QUALITY_DELETE,

    PRODUCT_CREATE,
    PRODUCT_READ,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    SUPPLIER_CREATE,
    SUPPLIER_READ,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,

    CLIENT_CREATE,
    CLIENT_READ,
    CLIENT_UPDATE,
    CLIENT_DELETE,

    STOCK_READ,
    STOCK_ENTRY,
    STOCK_EXIT,
    STOCK_ADJUSTMENT,
    STOCK_INVENTORY,
    STOCK_TRANSFER,

    PLAN_CREATE,
    PLAN_READ,
    PLAN_UPDATE,
    PLAN_DELETE,

    SUBSCRIPTION_TYPE_CREATE,
    SUBSCRIPTION_TYPE_READ,
    SUBSCRIPTION_TYPE_UPDATE,
    SUBSCRIPTION_TYPE_DELETE,

    COUPON_CREATE,
    COUPON_READ,
    COUPON_UPDATE,
    COUPON_DELETE,

    PROMOTION_CREATE,
    PROMOTION_READ,
    PROMOTION_UPDATE,
    PROMOTION_DELETE,

    SUBSCRIPTION_CREATE,
    SUBSCRIPTION_READ,
    SUBSCRIPTION_UPDATE,
    SUBSCRIPTION_CANCEL,
    SUBSCRIPTION_PAY,
    SUBSCRIPTION_RENEW,
    SUBSCRIPTION_VALIDATE
}
