package org.store.security.application.enums;

public enum PermissionCode {
    PROPRIETAIRE_ACCESS,
    EMPLOYE_ACCESS,
    EMPLOYE_CREATE,
    ADMIN_ACCESS,

    CATEGORY_PRODUCT_CREATE,
    CATEGORY_PRODUCT_READ,
    CATEGORY_PRODUCT_UPDATE,
    CATEGORY_PRODUCT_DELETE,

    QUALITY_CREATE,
    QUALITY_READ,
    QUALITY_UPDATE,
    QUALITY_DELETE,

    PRODUCT_CREATE,
    PRODUCT_READ,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    SUPPLIER_CREATE,
    SUPPLIER_READ,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,

    STOCK_READ,
    STOCK_ENTRY,
    STOCK_EXIT,
    STOCK_ADJUSTMENT,
    STOCK_INVENTORY,
    STOCK_TRANSFER
}
