CREATE TABLE country (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name         VARCHAR(100) NOT NULL,
    country_code CHAR(2)      NOT NULL UNIQUE,
    currency     CHAR(3)      NOT NULL,
    actif        BOOLEAN      NOT NULL DEFAULT TRUE
);

INSERT INTO country (name, country_code, currency) VALUES
-- West Africa (XOF)
('Sénégal',           'SN', 'XOF'),
('Côte d''Ivoire',    'CI', 'XOF'),
('Mali',              'ML', 'XOF'),
('Burkina Faso',      'BF', 'XOF'),
('Niger',             'NE', 'XOF'),
('Guinée-Bissau',     'GW', 'XOF'),
('Togo',              'TG', 'XOF'),
('Bénin',             'BJ', 'XOF'),
-- Central Africa (XAF)
('Cameroun',          'CM', 'XAF'),
('Gabon',             'GA', 'XAF'),
('Congo',             'CG', 'XAF'),
('Tchad',             'TD', 'XAF'),
('République Centrafricaine', 'CF', 'XAF'),
('Guinée Équatoriale','GQ', 'XAF'),
-- North Africa
('Maroc',             'MA', 'MAD'),
('Tunisie',           'TN', 'TND'),
('Algérie',           'DZ', 'DZD'),
('Égypte',            'EG', 'EGP'),
('Libye',             'LY', 'LYD'),
-- Sub-Saharan Africa
('Nigeria',           'NG', 'NGN'),
('Kenya',             'KE', 'KES'),
('Ghana',             'GH', 'GHS'),
('Afrique du Sud',    'ZA', 'ZAR'),
('Éthiopie',          'ET', 'ETB'),
('Tanzanie',          'TZ', 'TZS'),
('Ouganda',           'UG', 'UGX'),
('Rwanda',            'RW', 'RWF'),
('Mozambique',        'MZ', 'MZN'),
('Angola',            'AO', 'AOA'),
('Zambie',            'ZM', 'ZMW'),
('Guinée',            'GN', 'GNF'),
-- Europe
('France',            'FR', 'EUR'),
('Allemagne',         'DE', 'EUR'),
('Italie',            'IT', 'EUR'),
('Espagne',           'ES', 'EUR'),
('Portugal',          'PT', 'EUR'),
('Pays-Bas',          'NL', 'EUR'),
('Belgique',          'BE', 'EUR'),
('Royaume-Uni',       'GB', 'GBP'),
('Suisse',            'CH', 'CHF'),
('Suède',             'SE', 'SEK'),
('Norvège',           'NO', 'NOK'),
('Danemark',          'DK', 'DKK'),
('Pologne',           'PL', 'PLN'),
-- Americas
('États-Unis',        'US', 'USD'),
('Canada',            'CA', 'CAD'),
('Brésil',            'BR', 'BRL'),
('Mexique',           'MX', 'MXN'),
('Argentine',         'AR', 'ARS'),
('Colombie',          'CO', 'COP'),
-- Middle East
('Émirats Arabes Unis','AE','AED'),
('Arabie Saoudite',   'SA', 'SAR'),
('Qatar',             'QA', 'QAR'),
('Koweït',            'KW', 'KWD'),
('Turquie',           'TR', 'TRY'),
-- Asia
('Chine',             'CN', 'CNY'),
('Japon',             'JP', 'JPY'),
('Inde',              'IN', 'INR'),
('Corée du Sud',      'KR', 'KRW'),
('Singapour',         'SG', 'SGD'),
('Malaisie',          'MY', 'MYR'),
('Indonésie',         'ID', 'IDR'),
('Philippines',       'PH', 'PHP'),
('Thaïlande',         'TH', 'THB'),
('Vietnam',           'VN', 'VND'),
-- Oceania
('Australie',         'AU', 'AUD'),
('Nouvelle-Zélande',  'NZ', 'NZD');
