-- Fix country names that were stored with wrong encoding (UTF-8 read as Latin-1).
-- Using PostgreSQL U&'' Unicode escape syntax to avoid any encoding dependency.
UPDATE country SET name = U&'S\00E9n\00E9gal'              WHERE country_code = 'SN';
UPDATE country SET name = U&'C\00F4te d\2019Ivoire'        WHERE country_code = 'CI';
UPDATE country SET name = U&'Burkina Faso'                  WHERE country_code = 'BF';
UPDATE country SET name = U&'Guin\00E9e-Bissau'            WHERE country_code = 'GW';
UPDATE country SET name = U&'B\00E9nin'                     WHERE country_code = 'BJ';
UPDATE country SET name = U&'Guin\00E9e \00C9quatoriale'   WHERE country_code = 'GQ';
UPDATE country SET name = U&'Guin\00E9e Conakry'           WHERE country_code = 'GN';
UPDATE country SET name = U&'Maroc'                         WHERE country_code = 'MA';
UPDATE country SET name = U&'Tunisie'                       WHERE country_code = 'TN';
UPDATE country SET name = U&'Alg\00E9rie'                   WHERE country_code = 'DZ';
UPDATE country SET name = U&'\00C9gypte'                    WHERE country_code = 'EG';
UPDATE country SET name = U&'Libye'                         WHERE country_code = 'LY';
UPDATE country SET name = U&'\00C9thiopie'                  WHERE country_code = 'ET';
UPDATE country SET name = U&'Tanzanie'                      WHERE country_code = 'TZ';
UPDATE country SET name = U&'Ouganda'                       WHERE country_code = 'UG';
UPDATE country SET name = U&'Mozambique'                    WHERE country_code = 'MZ';
UPDATE country SET name = U&'Zambie'                        WHERE country_code = 'ZM';
UPDATE country SET name = U&'Allemagne'                     WHERE country_code = 'DE';
UPDATE country SET name = U&'Espagne'                       WHERE country_code = 'ES';
UPDATE country SET name = U&'Portugal'                      WHERE country_code = 'PT';
UPDATE country SET name = U&'Pays-Bas'                      WHERE country_code = 'NL';
UPDATE country SET name = U&'Belgique'                      WHERE country_code = 'BE';
UPDATE country SET name = U&'Royaume-Uni'                   WHERE country_code = 'GB';
UPDATE country SET name = U&'Su\00E8de'                     WHERE country_code = 'SE';
UPDATE country SET name = U&'Norv\00E8ge'                   WHERE country_code = 'NO';
UPDATE country SET name = U&'Danemark'                      WHERE country_code = 'DK';
UPDATE country SET name = U&'Pologne'                       WHERE country_code = 'PL';
UPDATE country SET name = U&'\00C9mirats Arabes Unis'       WHERE country_code = 'AE';
UPDATE country SET name = U&'Arabie Saoudite'               WHERE country_code = 'SA';
UPDATE country SET name = U&'Kou\00EFt'                     WHERE country_code = 'KW';
UPDATE country SET name = U&'Turquie'                       WHERE country_code = 'TR';
UPDATE country SET name = U&'Cor\00E9e du Sud'              WHERE country_code = 'KR';
UPDATE country SET name = U&'Indon\00E9sie'                 WHERE country_code = 'ID';
UPDATE country SET name = U&'Tha\00EFlande'                 WHERE country_code = 'TH';
UPDATE country SET name = U&'Nouvelle-Z\00E9lande'          WHERE country_code = 'NZ';
UPDATE country SET name = U&'Br\00E9sil'                    WHERE country_code = 'BR';
UPDATE country SET name = U&'Mexique'                       WHERE country_code = 'MX';
UPDATE country SET name = U&'Argentine'                     WHERE country_code = 'AR';
UPDATE country SET name = U&'Colombie'                      WHERE country_code = 'CO';
